(defun jh-start-gdb-current-buffer ()
  (interactive)
  (let ((command-string (file-name-nondirectory (file-name-sans-extension (buffer-file-name))))
        (filter-str (read-string "Filter: " nil 'my-history))
        )
    (other-buffer)
    (cd "/repo/ejonhes/radiosw/test/unitTest")
  (gdb (concat "gdb -i=mi --args ./" command-string " --gtest_filter=*" filter-str))
  ))
